### ISSUE TITLE
Add new Team Members to Team Page

### ISSUE THREAD

**Issue by Suri111200** [Software-For-Love/software-for-love-site#118]
We are currently missing a few team members.

Rudy Udovc - Finance Team
Hamzah Abouseta - Software Team
Arpit Thakkar - Software Team (No picture yet?)

Pictures can be found here: https://drive.google.com/drive/folders/1fiE9KNwgP1Q0notdQY8V2LZkFxT80gpt?usp=sharing

**Comment by arpitt2102** [comment]
Hii @Suri111200 , 
I will need LinkedIn and GitHub links.

**Comment by Suri111200** [comment]
Hi @arpitt2102 -- apologies, I've forgot to include them.

Rudy: https://www.linkedin.com/in/rudy-udovc-46b956159/

Hamzah: 
https://www.linkedin.com/in/hamzah-abouseta-65402b170/
https://github.com/hamzahabouseta
