### ISSUE TITLE
Change Projects Section

### ISSUE THREAD

**Issue by AvaneeshM** [Software-For-Love/software-for-love-site#132]
- Add projects section for the homepage
- Card design looks like the one in the blog page
- Change the background colour for the section
- Could look the same as the blog page

Refer To The Figma Design: https://www.figma.com/file/DPYi6BjNHgtPn3CUhYGRgx/SoftwareForLove-Design?node-id=0%3A1

**Comment by Suri111200** [comment]
Forgot to mention this in the meeting-- I want to clarify that the Blog page and Projects page will be 2 separate pages and will have different purposes in the future. I'm not sure if this is clear, but we can have a quick meeting to discuss this if you'd like. @AvaneeshM @NutanNimkar
