### ISSUE TITLE
Change "Contact Us" Form

### ISSUE THREAD

**Issue by Suri111200** [Software-For-Love/software-for-love-site#34]
- Remove Organization, Phone Number, Preferred Method of Contact fields
- Make name, message field mandatory

**Comment by Renfrew100** [comment]
Would this just be for the volunteers page?

**Comment by kandloic** [comment]
No, on both pages. I'll remove the fields from the contact form component.

**Comment by kandloic** [comment]
> * Make name, message field mandatory

Shouldn't the email address be mandatory as well?

**Comment by Suri111200** [comment]
> 
> Shouldn't the email address be mandatory as well?
> 
> 
> 
> 

Yes, that would make sense, especially since we're removing the phone number field anyways. Please do this!
