### ISSUE TITLE
Add Google Analytics Support 

### ISSUE THREAD

**Issue by CoderHahs** [Software-For-Love/software-for-love-site#89]
Estimated Time: 3h

- Make a new branch
- Add Google Analytics support to the Software For Love Website
- Share analytics info with team@softwareforlove.com

- Add a banner at bottom of page that states that we use cookies to analyze data traffic and to better serve our target audience
- Banner must have a hyperlink to the terms page : https://www.softwareforlove.com/terms
- Banner must be able to be dismissed (X in the corner)

**Comment by Suri111200** [comment]
@sultanoloyede This branch has the updated terms provided by the legal team. Feel free to work off here: https://github.com/Software-For-Love/software-for-love-site/tree/Soorya/analytics
